version: '3.4'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      PORT: 5000
